In [2]:
# Experiment 1
import numpy as np

# Create NumPy array using Python list
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

# Experiment 2
import numpy as np

zero_matrix = np.zeros((3,4))
one_matrix = np.ones((2,5))

print("3x4 Zero Matrix:")
print(zero_matrix)
print("Shape:", zero_matrix.shape)

print("\n2x5 One Matrix:")
print(one_matrix)
print("Shape:", one_matrix.shape)

# Experiment 3
import numpy as np

arr = np.arange(1,13)

print("Original Array:", arr)
print("Shape:", arr.shape)

reshaped = arr.reshape(3,4)

print("\nReshaped 3x4 Matrix:")
print(reshaped)
print("Shape:", reshaped.shape)

# Experiment 4
import numpy as np

arr = np.array([53, 19, 91, 8, 33, 6, 12, 70, 57, 63])

print("Array:", arr)

print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

# Experiment 5
import pandas as pd

data = {
    "Student Name": ["Amit", "Riya", "Neha", "Karan"],
    "Marks": [85, 92, 78, 88]
}

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nData Types:")
print(df.dtypes)

# Experiment 6
import pandas as pd
data = {
    "ID":[1,2,3,4,5,6,7,8,9,10],
    "Name":["Amit","Riya","Neha","Karan","Rahul","Sneha","Aman","Pooja","Nitin","Kavya"],
    "Marks":[85,92,78,88,90,81,75,89,84,91]
}

df = pd.DataFrame(data)

df.to_csv("data.csv", index=False)

print("data.csv created successfully")

df = pd.read_csv("data.csv")

print("First 5 Records:")
print(df.head())

print("\nLast 5 Records:")
print(df.tail())

# Experiment 7
import pandas as pd

df = pd.read_csv("data.csv")

print(df.info())

print("\nNumber of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nMissing Values:")
print(df.isnull().sum())

# Experiment 8
import pandas as pd

df = pd.read_csv("data.csv")

print("Statistical Summary:")
print(df.describe())

Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64
3x4 Zero Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

2x5 One Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)
Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped 3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)
Array: [53 19 91  8 33  6 12 70 57 63]
Minimum: 6
Maximum: 91
Mean: 41.2
Sum: 412
DataFrame:
  Student Name  Marks
0         Amit     85
1         Riya     92
2         Neha     78
3        Karan     88

Data Types:
Student Name    object
Marks            int64
dtype: object
data.csv created successfully
First 5 Records:
   ID   Name  Marks
0   1   Amit     85
1   2   Riya     92
2   3   Neha     78
3   4  Karan     88
4   5  Rahul     90

Last 5 Records:
   ID   Name  Marks
5   6  Sneha     81
6   7   Aman     75
7   8  Pooja     89
8   9  Nitin     84
9  10  Kavya     91
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data